### PR TITLE
Add mini player

### LINKED ISSUE #10: Add basic media controller
Might need to be a double width tile (like the blind control).

Ideally would have 3 lines of text for track, artist, album and then a set of icons for PLAY, PAUSE. PREV, NEXT.

We could add volume control as well, or make that another tile type you setup in conjunction with the media tile if you wish.

### PR DESCRIPTION
**Pull request by moinmoin-sh**
added Mini Player as discussed in #10 

`Previous` and `Next` buttons send mqtt stat\ payloads; 

`{"screen":1,"tile":5,"type":"button","event":"prev"}`
`{"screen":1,"tile":5,"type":"button","event":"next"}`

further changes : 
- added `MUSIC `tile type to serve as a `link tile` to link to a complete `player screen` as shown in #10 
- enabled button event `hold ` for all tiles

`{"screen":1,"tile":5,"type":"button","event":"single","state":"off"}`
`{"screen":1,"tile":5,"type":"button","event":"hold","state":"off"}`

Not sure about the icons I picked, open for suggestions.

closes #10

### CODE REVIEW

**Comment by moinmoin-sh** [comment]
The latest commit  [95ddeb3](https://github.com/moinmoin-sh/OXRS-MM-WallPanel-ESP32-FW/pull/25/commits/95ddeb3f9ddeccb3abf6a13383a8c8837983e1bd) replaces the swipe in the footer area to switch screens by a drop down list.
Click on the middle footer area opens a drop down that shows all allocated screens by their name in a list. The desired screen can then be selected and the display changes to that. This allows to select any screen from any screen and is the most flexible way to change screens manually.
The swipe is not very reliable and I really prefer to eliminate it.

**Comment by sumnerboy12** [comment]
Gave it a quick test just now - looks really good. Everything seems to work as expected. One thing I would find handy is if the media tile generated `"type":"media"` events, rather than `"type":"button"` - the reason being I can build a generic sub-flow which can take events from any sort of tile and translate to something useful - e.g. a volume/level tile to mute and control volume, a media tile to play/pause/skip/back etc.

But if both the level and media tiles generate `button` events then I can't differentiate without having to store what each tile type is in NodeRED. Thoughts?

**Comment by moinmoin-sh** [comment]
I think adding `tiletype` to the payloads that are coming from a tile is the most universal approach.

What about the screen drop down instead of swipe? Do you agree?

**Comment by plains203** [comment]
I don’t have an issue with adding the type. It might simplify flows in some cases but if you have 2 of the same type of tile and are controlling different devices then you’ll still want to track it by tile. So I guess that would mean instead of a “single” action on hitting the player button it would then be “play” but then you hold that and what does it generate? So yeah I can see pro’s and con’s.

**Comment by sumnerboy12** [comment]
I'm not sure about the drop-down for screen selection. It is easier to
control but it is two actions to change screen, whereas swipe is just one.

Seems a little clunky having to click the footer and then click again.

But I do agree swiping is a little tricky with quite a small target.

**Comment by moinmoin-sh** [comment]
added the tiletype to payloads related to tiles.
Sample payloads: 


```
{"screen":1,"tile":3,"tiletype":"speaker","type":"button","event":"single","state":"off"}
{"screen":1,"tile":3,"tiletype":"speaker","type":"level","event":"change","state":0}
{"screen":1,"tile":3,"tiletype":"speaker","type":"level","event":"change","state":0}
{"screen":1,"tile":3,"tiletype":"speaker","type":"level","event":"change","state":1}
{"screen":1,"tile":3,"tiletype":"speaker","type":"level","event":"change","state":2}
{"screen":1,"tile":3,"tiletype":"speaker","type":"level","event":"change","state":3}
{"screen":1,"tile":3,"tiletype":"speaker","type":"level","event":"change","state":4}
{"screen":1,"tile":5,"tiletype":"player","type":"button","event":"prev"}
{"screen":1,"tile":5,"tiletype":"player","type":"button","event":"next"}
{"screen":1,"tile":5,"tiletype":"player","type":"button","event":"prev"}
{"screen":1,"tile":5,"tiletype":"player","type":"button","event":"next"}
{"screen":1,"tile":6,"tiletype":"dropdown","type":"dropdown","event":"change","state":3}
{"screen":1,"tile":2,"tiletype":"light","type":"button","event":"hold","state":"off"}
{"screen":1,"tile":4,"tiletype":"music","type":"button","event":"hold","state":"off"}
{"screen":1,"tile":1,"tiletype":"dropdown","type":"button","event":"hold","state":"off"}
```
Please check if this works better for your NR-flows.

I tried to keep as close as possible to our OXRS standard. If necessary we can redefine the stat/ structure.

**Comment by moinmoin-sh** [comment]
> I'm not sure about the drop-down for screen selection. It is easier to
> control but it is two actions to change screen, whereas swipe is just one.
> 

One swipe is only true for the previous or next screen. As soon as you need to switch further the drop-down is equal or less touches (never more than 2)
You also get random access to screens.
In general I think for this screen touch is better than swipe - that's just me.

**Comment by sumnerboy12** [comment]
Yep that is a valid point. But I don't plan to have too many screens per
panel, I think the best UX is a single screen for main functions in the
room with possible sub screens for less used functions.

But I am happy with what you have done.

**Comment by sumnerboy12** [comment]
The addition of `tiletype` will be very useful for my flows - thanks for that. I think we might need to address the payload format sooner rather than later tho. I will have a think and come up with a proposal - might even do a PR.

**Comment by plains203** [comment]
The tiletype addition seems well thought through. I like that it doesn't upset the way I am using it now and adds further flexibility in the way that sumnerboy is using it. 

I like the new screen select option instead of swiping. It feels easier. I am not sure how often I would use it, certainly I am today with testing. I like the idea of laying the screen out in such a way that I can tap my way through and then potentially set the screen via cmnd based on an event.

**Comment by plains203** [comment]
This latest version seems to have broken my ability to push commands to it. 
"[wpan] failed to deserialise mqtt json payload"

**Comment by moinmoin-sh** [comment]
That's odd. I used it before I pushed the latest version.
Please double check. If it still doesn't work please share the failing payload(s).

**Comment by moinmoin-sh** [comment]
I'm going to do some tidy up and merge later today

**Pull request merged**
