### PR TITLE
add remote control screen

### PR DESCRIPTION
**Pull request by moinmoin-sh**
added tile type REMOTE
click on this displays a modal screen with a remote control navigation panel

First cut of a Remote Control screen.

these are the stat/ payloads for the various buttons 

```
{"screen":1,"tile":1,"tiletype":"remote","type":"up","event":"single"}
{"screen":1,"tile":1,"tiletype":"remote","type":"down","event":"single"}
{"screen":1,"tile":1,"tiletype":"remote","type":"left","event":"single"}
{"screen":1,"tile":1,"tiletype":"remote","type":"right","event":"single"}
{"screen":1,"tile":1,"tiletype":"remote","type":"ok","event":"single"}
{"screen":1,"tile":1,"tiletype":"remote","type":"info","event":"single"}
{"screen":1,"tile":1,"tiletype":"remote","type":"list","event":"single"}
{"screen":1,"tile":1,"tiletype":"remote","type":"back","event":"single"}
{"screen":1,"tile":1,"tiletype":"remote","type":"home","event":"single"}

```

grafik

### CODE REVIEW

**Comment by plains203** [comment]
Flashed it and tested it. Feels great to use and I am impressed with the layout. I do wonder if there could be some feedback on the screen when the button is pressed. Maybe the button could flash or something?

**Comment by plains203** [comment]
Also would it be possible to add the button hold event to these please?

**Comment by moinmoin-sh** [comment]
The above comments clearly address issues that need to be solved and I have on my list. I wanted to collect some feedback first to see if the concept works before spending more effort in this. 
Please keep on testing and share your experience.

**Comment by plains203** [comment]
> The above comments clearly address issues that need to be solved and I have on my list. I wanted to collect some feedback first to see if the concept works before spending more effort in this. Please keep on testing and share your experience.

No worries! Currently coding the flows for control of Kodi. I'll share them in the discord later.

**Comment by moinmoin-sh** [comment]
> Also would it be possible to add the button hold event to these please?

done

**Comment by plains203** [comment]
Working really well in conjunction with the mini player, level control and the drop down box in my situation. It could have extra controls on there but I think that makes it less universal potentially?

**Comment by sumnerboy12** [comment]
This looks great Moin - the only comments I have echo what James mentioned above, with one extra... the Home icon (top left) looks a little bit like an UP arrow. Is that an icon or have you manually drawn that? Could you add a little door or maybe a chimney? Something to differentiate it from that arrow shape. Very very minor!

**Comment by plains203** [comment]
It does make it easier to see. I do wonder if flashing the shaded part of the button flashing instead of the icon might be better for visibility. The on colour might not be suitable for that though. I am not sure what my thoughts are re additional tiles on the modal screen. It might work well as is and as an additional supertile that say 4x4 that you can then add two tiles above or below on a standard screen. Not sure. I like the new boot logo and the shape of the buttons. Makes it more unique.

**Comment by moinmoin-sh** [comment]
Yes. coloring that what looks like the button would be nicer, but I couldn't make that work.
That what looks like buttons is a fake. What you see is an opaque layer of an image with transparent cutouts that form the icons. Behind the cutouts are illuminated buttons with larger touch area and make the color of the icon change. Making the buttons being real segments of a circle would need a more complex concept which is above my limited skills. Long story short, I would like to stay with it as is for now.

**Comment by plains203** [comment]
As it is is perfectly fine.

**Pull request merged**
