### PR TITLE
Add ethernet support

### PR DESCRIPTION
**Pull request by austinscreations**
this is what's needed for this code to support ethernet

once the pull request is merged into OXRS.IO/Ethernet library this will work properly for ethernet.

### CODE REVIEW

**Review by sumnerboy12 — APPROVED** [review]
Looks good to me (haven't tested)

**Comment by austinscreations** [comment]
> Looks good to me (haven't tested)

i totally forgot you have the shield too.
just point the sketch at the Ethernet library changes branch / commit and you'd be able to test if you wanted.

**Comment by moinmoin-sh** [comment]
@sumnerboy12 could you please install your ethernet/POE shield and verify Austins changes. Just to have a second pair of eyes looking at it. Thanks

**Comment by sumnerboy12** [comment]
I tested this on my WT32 with the POE shield but it got into a boot loop. I built this branch of the WallPanel firmware with the following change to `platformio.ini`;
```
  https://github.com/austinscreations/Ethernet#add-spi-bus-support
```

When I upload the firmware and run it just keeps rebooting. I tried with the ethernet cable plugged in and out, same thing.

**Review by sumnerboy12 — CHANGES_REQUESTED** [review]
See comments on PR - tested and have a boot loop

**Comment by sumnerboy12** [comment]
NOTE: I was getting an IP address assigned by DHCP, so ethernet was working. I was even seeing a connection to my MQTT broker. But after a few seconds it reboots and starts over again.

**Comment by sumnerboy12** [comment]
```[wpan] starting up...
Hello Arduino! V8.3.0
I am LVGL_Arduino
Setup done
[wpan] {"firmware":{"name":"OXRS-AC-WallPanel-ESP-FW","shortName":"OXRS Wall Panel","maker":"Austins Creations","version":"DEBUG-ETH"}}
[wpan] ethernet mac address: A4:E5:7C:E0:AE:EF
[wpan] ip address: 192.168.40.234

assert failed: spinlock_acquire spinlock.h:122 (result == core_id || result == SPINLOCK_FREE)


Backtrace:0x40083dfd:0x3ffb23200x4008cf61:0x3ffb2340 0x4009244d:0x3ffb2360 0x4008feef:0x3ffb2490 0x40091dd9:0x3ffb24d0 0x40091efb:0x3ffb24f0 0x40092157:0x3ffb2510 0x4013d2da:0x3ffb2530 0x40112d26:0x3ffb2570 0x4010b7c7:0x3ffb25b0 0x4010bb6c:0x3ffb25f0 0x4010877d:0x3ffb2620 0x4010b58e:0x3ffb2660 0x4010500d:0x3ffb26c0 0x4010507d:0x3ffb27a0 0x4010afaf:0x3ffb27c0 0x401110d6:0x3ffb2800 0x40115e3d:0x3ffb2820```

**Comment by austinscreations** [comment]
I'll try again on my end and see if i missed something in my PRs

**Comment by moinmoin-sh** [comment]
>I built this branch of the WallPanel firmware with the following change to `platformio.ini`;
> 
> ```
> 
>   https://github.com/austinscreations/Ethernet#add-spi-bus-support
> 
> ```
> 

I hope that you made the changes to OXRS_WT32.* as well ?

**Comment by austinscreations** [comment]
I've actually had it fail to properly use all the commits to the branch when using `https://github.com/austinscreations/Ethernet#add-spi-bus-support`
try compiling with
`https://github.com/austinscreations/Ethernet.git#56f9cc4`

Ideally the line change won't be needed once the pr can be moved to oxrs.io (pending testing and approval)

**Comment by moinmoin-sh** [comment]
I totally missed from your PR that an update of the Ethernet library is required. 
Wouldn't that Ethernet PR something for the original library to take advance of it by all users?

**Comment by austinscreations** [comment]
> 

yes, it would.
i tried submitting a PR but found out that i didn't have platformIO properly setup for my commits so they aren't under my username which means i couldn't sign their license agreement. (fixed now) and it failed all their automatic tests which are for AVR microcontrollers.

when i have time i'll go back and spend time troubleshooting and reopen a PR for the main library. in teh meantime i have a PR open for the OXRS.io fork that implements the needed changes.

**Comment by sumnerboy12** [comment]
> I hope that you made the changes to OXRS_WT32.* as well ?

What changes are they?

**Comment by austinscreations** [comment]
> 

i think moins referring to the changes i'm making in this PR.
but i'm betting you've just opened the branch in platformIO thus the changes should already be made.
and thus the only change needed for testing is changing the link for ethernet library.
and once the Ethernet library is pr is done it won't be an issue.

**Comment by sumnerboy12** [comment]
Yep - I was building from this branch directly, with a reference to your ethernet PR/branch in `platformio.ini`.

**Comment by austinscreations** [comment]
have you had a chance to try this link instead?
`https://github.com/austinscreations/Ethernet.git#56f9cc4`

**Comment by sumnerboy12** [comment]
That is the commit it was looking at - I checked the dependency tree.

**Comment by austinscreations** [comment]
example

this is what shows for me,
and ran the clean and reupload of debug-eth and it's running no issue, connects to dchp and then shows mqtt connected.
i have two tiles loaded that i can tap no issues.

**Review by sumnerboy12 — APPROVED** [review]
Tested using a build from @austinscreations and it appears to be working fine. I must have messed up my local build somehow.

**Comment by sumnerboy12** [comment]
You should probably update `platformio.ini` to point at your Ethernet library change/branch - otherwise building this won't include those changes, until that PR is merged?

**Comment by austinscreations** [comment]
this PR? [https://github.com/OXRS-IO/Ethernet/pull/2]() @sumnerboy12 or do i need to spend time troubleshooting all the AVR checks that they want a PR to pass in the arduino-library that the oxrs fork is based off of.

**Comment by austinscreations** [comment]
ok, for the time being keep this open and I'm going to work on finalizing changes to Ethernet that doesn't show errors for AVR compilation. and so that we don't have to keep my fork added to the PlatformIO (reduce the libraries needing maintenance.)

**Comment by moinmoin-sh** [comment]
> You should probably update `platformio.ini` to point at your Ethernet library change/branch - otherwise building this won't include those changes, until that PR is merged?

I tried to do that, but unfortunately it doesn't work because Austins Ethernet library branch doesn't contain the patch for the EthernetServer which @sumnerboy12 added to the Ethernet library hosted on OXRS.io

**Comment by austinscreations** [comment]
All the changes have been made to the library and been pushed back to oxrs.io library so that link should work for compiling now and no longer require changing `platformio.ini` file

**Comment by moinmoin-sh** [comment]
I just recognized that. Building from your repro with the OXRS Ethernet library leads to the same error that Ben had. Could you please send me your working binary, just to make sure there isn't something else. (I connected my W5500 shield to the WT32 for testing)

**Comment by austinscreations** [comment]
Ok, will check when I get home. Do note when connecting w5500 it uses non-standard spi pins because the wt32 has the i2c uses some of the regular pins.

**Comment by moinmoin-sh** [comment]
I'm well aware of the unusual connection and copied it from your POE-Shield. I get and IP from DHCP which tells me that it must be working to some extend. A known working binary as you used it and sent to Ben would help to rule out any HW-issues that I might have caused.

**Comment by austinscreations** [comment]
Managed to download the bin I sent to Ben to my phone and sent it to you on discord

**Comment by moinmoin-sh** [comment]
for the records : that binary works for me as well - Austin will investigate.

**Comment by austinscreations** [comment]
tried digging into this a little tonight.
i've gotten as far as knowing that the failure happens at `_api.begin();` 
no idea why. tried disabling the connection to Ethernet and it doesn't make a difference.
added `if (!SPIFFS.begin())` with serial debug, and spiffs was working.
no clue whats going on.
using the IDF.py program it gives a little detail about the serial stack dump, and from what i can tell is it's having issue with SPI Flash reading.
```
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400919d8  PS      : 0x00060a33  A0      : 0x80091e70  A1      : 0x3ffb25d0
A2      : 0x3f800014  A3      : 0xffffffff  A4      : 0xfffffffc  A5      : 0x0000400c
A6      : 0x00060e20  A7      : 0x00000001  A8      : 0x3f803628  A9      : 0x3f800414
A10     : 0x00000008  A11     : 0x00000000  A12     : 0x0000400d  A13     : 0x3f803630
A14     : 0x00060a23  A15     : 0x00000000  SAR     : 0x00000009  EXCCAUSE: 0x0000001d
EXCVADDR: 0x0000000b  LBEG    : 0x4008abd0  LEND    : 0x4008abdb  LCOUNT  : 0x00000000
0x4008abd0: spi_flash_common_write_qe_sr at C:/Espressif/frameworks/esp-idf-v4.4.1/components/spi_flash/spi_flash_chip_generic.c:642

0x4008abdb: spi_flash_common_write_qe_sr at C:/Espressif/frameworks/esp-idf-v4.4.1/components/spi_flash/spi_flash_chip_generic.c:643

Backtrace:0x400919d5:0x3ffb25d00x40091e6d:0x3ffb25f0 0x4009209a:0x3ffb2610 0x40084261:0x3ffb2630 0x4009247d:0x3ffb2650 0x40108a06:0x3ffb2670 0x4010a391:0x3ffb2690 0x4010b2f1:0x3ffb2720 0x4010c1fb:0x3ffb2740 0x40112989:0x3ffb27b0 0x40115fc6:0x3ffb2820
0x40084261: esp_cpu_configure_region_protection at C:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/cpu_util.c:94 (discriminator 3)
```

and the reason i was able to compile a working version before was because i was still using `PLATFORM: Espressif 32 (4.2.0) > Espressif ESP-WROVER-KIT`
error is present on `PLATFORM: Espressif 32 (4.4.0) > Espressif ESP-WROVER-KIT`

**Comment by austinscreations** [comment]
closing this, as I'll have MANY changes to push with my fixes to things. and the best thing to do will be to just pull a fresh updated copy of the code and push the changes to that.

**Pull request closed without merging**
