### PR TITLE
image on tile

### PR DESCRIPTION
**Pull request by moinmoin-sh**
### EXPERIMENTAL feature

this allows to display a custom image on a tile.

`cmnd\  {"setstate":[{"screen":"1", "tile":"1", "image":"<encodeBase64(img.png)>", "zoom":"100"}]}`

`"image"; encodeBase64(image.png)  `    (size of the encoded image < 16k)
`"zoom": 50 ... 200 [%] `  scales the image
the image is centered within the destination tile
larger images will be cropped to the tile size

be aware : this is experimental !

### CODE REVIEW

**Comment by sumnerboy12** [comment]
Gave this a quick test and it seems to be working. Icons are drawn in black, how do the standard/custom icons get inverted when displayed?

Think this could be very useful tho. Could we have the option to define when there icon is positioned? So you could use this feature to draw icons in the standard spot (top-left) but have them dynamically updated (e.g. weather condition, battery level, etc).

**Comment by sumnerboy12** [comment]
Ok cool - that is pretty much what I expected. All good.

For `pos` could we have `pos_x` and `pos_y` as offsets from `0,0`?

**Comment by moinmoin-sh** [comment]
Yes we can. Where would you like the origin (0,0)?  Typical is `top/left` (y would be negative)   or` center` where x and y are signed integer
I think I prefer **center  = 0,0**

**Comment by sumnerboy12** [comment]
In my mind it would be `top/left` == `0,0` and then the `pos_x` and `pos_y` would be positive ints offset from that point. I realise that is not strictly correct, but for this scenario it seems logical to me.

I do think `center` by default is sensible, and then you optionally override with `0,0` to place the image in the same place a normal icon would be displayed, with the ability to place it anywhere with other offsets.

Otherwise if the origin is `center` which equals `0,0` it will become tricky for someone to position the image in the same place as a normal icon.

**Comment by moinmoin-sh** [comment]
Sorry, but that doesn't sound logical to me. 
My idea of this was using a tile as a kind of "picture frame" not as an icon replacement - which is a good use case as well.
To not overcomplicating things I would like to keep 0,0 as default and origin = center. The outer  most positioning (as for an icon replacement) of the image edge could be addressed by entering a high value which would be interpreted by the FW to align the edge of the image to the edge of the tile. This would allow to position the image easily to each edge you like which would be hard if top/left would be the origin.

**Comment by sumnerboy12** [comment]
I can see this being useful for dynamic icon/images

**Comment by sumnerboy12** [comment]
But happy with whatever you decide in terms of where the origin is etc.

**Comment by moinmoin-sh** [comment]
may be it's worth to seperate these two use cases and define a "dynamic_icon" for the tile. 
- image replaces configured icon via setstate
- is allways positioned top/left
- no zoom required (?)
- reverts to configured icon if set to NULL 
- appearance doesn't change with state

**Comment by sumnerboy12** [comment]
Yep that sounds like a good idea. Maybe call the original `background_image`?

**Comment by moinmoin-sh** [comment]
Yes, that's what it basically is (and how I called in FW)

**Comment by plains203** [comment]
Do we have an option to define a split tile like the level tile or mini player tile?

**Comment by moinmoin-sh** [comment]
Not sure if I fully understand?
You can put an image on each tile type. The area covered depends on the image size. The image can have any rectangular size. With the posx/y  parameter (as discussed above, but not available yet) you can position the image on the tile as you like.
Does that cover your question?

**Comment by plains203** [comment]
Yeah sounds reasonable. I haven't really thought through the use case properly but I think that would work fine.

**Comment by sumnerboy12** [comment]
Sounds very flexible. Just to confirm, the image position is relative to the center of the image? I.e. 0,0 places the center of the image at the center of the tile.

**Comment by moinmoin-sh** [comment]
The latest commit allows icons to be changed on the fly via MQTT
cmnd\  `{"setstate":[{"screen":1, "tile":1, "icon":"<name>"}]} `  <name> = `built-in` or `custom` named icon (custom icon has to be loaded earlier)
This can (optional) be combined with a state and color.
`{"setstate":[{"screen":1, "tile":1, "state":"off", "color":[255,0,0], "icon":"_bulb"}]} `
The selected icon is bound to the state that is included in the cmnd or if omitted to the recent state of the button.
The icon can be reverted to the default (set during config) with an empty key `"icon":""`.

This feature can be usefull to set different icons for `off `and `on `or setting `"3rd"` states like `"blindOpen"` , `"blindClosed" `, `"blindHalf"`,

Note: This works for icons only which are colored adn switched automatically depening on the tile state.

**Comment by sumnerboy12** [comment]
Dynamic tile icons will be very useful - great feature!

**Pull request merged**
