### PR TITLE
added level control overlay screen

### PR DESCRIPTION
**Pull request by moinmoin-sh**
proposal for a "universal" level control
[LevelControl.pdf](https://github.com/moinmoin-sh/OXRS-MM-WallPanel-ESP32-FW/files/8661954/LevelControl.pdf)

### CODE REVIEW

**Comment by moinmoin-sh** [comment]
this could be an alternative "in line" layout (not fully worked out, just a sketch)

grafik

**Comment by plains203** [comment]
As far as I can see you proposed flow should be workable. I would expect the screen to know my state prior to long press, I push the state to the screen anytime an item is updated. It won't hurt to request it again though and ensure it's current or for people using it differently.

**Comment by sumnerboy12** [comment]
Should this PR be closed now?

**Comment by moinmoin-sh** [comment]
was replaced by on-tile level control

**Pull request closed without merging**
