### PR TITLE
Revisit json structures

### LINKED ISSUE #40: add tile type BUTTON_LEFT_RIGHT similar to up/down
possible use cases

-    sliding door
-    gate

### LINKED ISSUE #42: Add a reboot button on the settings page
If the device gets in a bad state and won't reconnect (I have seen this today when restarting my WiFi AP - a separate issue with WiFi auto-reconnect) there is no easy way to reboot for wall mounted devices.

A little button on the settings page which lets you force reboot would be helpful in this scenario.

### PR DESCRIPTION
**Pull request by moinmoin-sh**
I think I have covered everything.

Please check if the code aligns to what we have negotiated and if it works as expected. 

Starting on page 13 of `Austins to do list` , labeled  **Final Implementation**, it shows all new json payloads. The "working" part of the document can be deleted and the "Final" list should be kept as part of the documentation.
 There are some comments in redish color. I removed the `mediaPlayer` style because that is just a special of the more generic  `buttonPrevNext` style. A player style outlined tile can be created with the `dynamic tile feature` which allows different icons for state `on `and `off`. 
```json
{"tiles":[{"screen":"1", "tile":"1","state":"on","icon":"_pause"}, {"screen":"1", "tile":"1","state":"off","icon":"_play"} ]}
```
This method can be used for many other tiles as well like `lightOn/Off`  `windowOpen/closed`

The icons well be revised shorly. the LVGL group released 8.3.0 today and will start to work on v9 imediately. There will be breaking changes for the png image handling which I have to integrate as soon as it's available. So no work on new images/icons for now.

closes #40 
closes #42

### CODE REVIEW

**Comment by plains203** [comment]
I have now had a chance and made some comments in the document.

**Comment by moinmoin-sh** [comment]
please check my comments

**Comment by plains203** [comment]
Your proposals look good moin

**Comment by moinmoin-sh** [comment]
I hope I got everything right. The document is updated, left the comments in for reference until it's done.

The new feature SELECTOR allows to pick from a list which is schown as a little roller on top of the icon in the same manner as the level bar is shown. The 2 buttons can then be used to scroll thru the list and pick the desired item (function). This is usefull for kind of multi step switches as typical for fans or AC (low / medium / high) or if a selection has to be made between some numbers. The list entries should be short to fit on the small roller.

**Review by sumnerboy12 — APPROVED** [review]
Too much to review in detail - more than happy with the changes tho (as outlined in Austin's doc). Great work as usual Moin!

**Pull request merged**
