### PR TITLE
integrated on-tile level control

### LINKED ISSUE #11: Add volume control
Nice to have a dedicated volume tile type as I think this would be a common use-case. 

Just a couple of PLUS/MINUS buttons with the current volume % displayed.

### PR DESCRIPTION
**Pull request by moinmoin-sh**
- new check box in config to enable on-tile controls
- additional parameter in cmnd/ setState  "level":nnn
-  publishes level change event to state/

closes #11

### CODE REVIEW

**Comment by moinmoin-sh** [comment]
I had to move the level label to the top of the ub/down buttons because in the center it was not visibible when the up button was pressed.

**Comment by plains203** [comment]
In it's current form if you update the tile level state that change is not reflected on the tile until you hit one one of the up or down buttons. It appears swapping screens also doesn't solve this. The config otherwise seems to work nicely.

**Comment by moinmoin-sh** [comment]
That's intended. The state `level `belongs to the bar visualisation and used to sybchronize the bar with the HA/NR. The state `subLabel ` belongs to the user who can updated this with whatever he wants. If you would like to synchronize both you have to send a cmnd/  `setStatus `with `subLabel `and `level `set like this
  `'{"setstate":[{"screen":1, "tile":3, "sublabel":"33 %", "level":33}]}'`
The FW uses the sublabel only when the up/down buttons are used and the bar visualisation is shown.

**Comment by sumnerboy12** [comment]
Could we try these arrows for the up/down buttons? 
image

**Comment by plains203** [comment]
> That's intended. The state `level `belongs to the bar visualisation and used to sybchronize the bar with the HA/NR. The state `subLabel ` belongs to the user who can updated this with whatever he wants. If you would like to synchronize both you have to send a cmnd/ `setStatus `with `subLabel `and `level `set like this
> `'{"setstate":[{"screen":1, "tile":3, "sublabel":"33 %", "level":33}]}'`
> The FW uses the sublabel only when the up/down buttons are used and the bar visualisation is shown.

Ah so what you’re saying is that the sublabel is used as feedback for the level state change buttons and because I never send it a sub label it just leaves the last value there. Originally I was thinking this was inconsistent with the rest of the screen but now it makes sense. Saves having the sublabel state saved as a variable and reverted once the level indicator bar is gone. Thanks 😊

**Comment by moinmoin-sh** [comment]
Having the nuneric display together with the bar makes it easier for the user to focus. Only on place to look at.
The % sign is left out by design. Makes it cleaner to display and watch.
The sub Label is now free from internal updates which should eliminate confusion.
I left the suppression of sub label outputs during button press for now - see how it feels

**Comment by sumnerboy12** [comment]
This looks fantastic Moin - really like the change - very easy to use and keep track of what is happening. Interested to hear the others thoughts on the _moving level label_ - I am not convinced it adds value and is a little distracting - the first time I saw it I thought there was a glitch in the rendering as I wasn't expecting it to move.

I am wondering if the sub-label should be able to be updated now - since it wouldn't overwrite anything - and means if you are displaying the level in the sub-label it will be updated during a long level change (i.e. press + hold).

I think any updates to the tile `level` should be suppressed however, as that is being directly controlled by the tile during a level change event.

E.g. in my flows I periodically query my amplifier to get the current volume and mute status, and send updates to the volume tile (every 1s). This includes `state` (mute or not), `level` (volume) and `subLabel`. So the tile would need to ignore the `level` if it was in the middle of a change event, but still process the `state` and `subLabel` updates. If that is possible?

**Comment by moinmoin-sh** [comment]
Could you please test if the latest update does what you're asking for. I can't test ATM.

If the moving numeric level is felt distracting I could pin it to the center, but I really want to have it close to the bar.

**Comment by sumnerboy12** [comment]
Yes - will test now - I think make a little video like you did last time showing how it works now and get feedback. I personally think I would prefer it static, but I don't have a strong opinion.

**Comment by moinmoin-sh** [comment]
Not all complains are fixed. Don't want another terrible feedback.

**Comment by plains203** [comment]
I like the addition of the level next to the bar. I second that it would be nice to have that pinned rather than following the bar, I feel it distracts a bit and makes the bar look less relevant and clear as a level indicator. Now that the sub label is disconnected from the level action I feel the suppression can change. I know in my use case where I have a state change node-red instantly sends an update to the screen and this is then not applied in this version. I think suppression of a level update cmnd might be of use as noted by sumnerboy. In all, looks good.

**Comment by plains203** [comment]
The new changes look good.
https://youtu.be/_bVYqJaDIy8

**Comment by moinmoin-sh** [comment]
I have integrated the requirement from Chris that the main label should be on the bottom if there is no subLabel to show.
Please see how you like it and comment please.
TBH  I don't like it. I prefer the fixed position as we have.

**Comment by moinmoin-sh** [comment]
The closed event looks like this : 
`{"screen":0,"type":"msgbox","event":"change","state":"closed"}`
`screen `is allways `0 `because the msgBox is not screen related and I wanted to keep the event format

**Pull request merged**
